# Generated by Django 2.2 on 2019-05-07 04:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_op_name', models.CharField(default='Anonymous', max_length=150)),
                ('post_heading', models.CharField(max_length=150)),
                ('post_body', models.CharField(max_length=1000)),
                ('post_time', models.DateTimeField(default=datetime.datetime(2019, 5, 7, 9, 57, 1, 592779))),
                ('post_op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=150)),
                ('comment_time', models.DateTimeField(default=datetime.datetime(2019, 5, 7, 9, 57, 1, 592779))),
                ('comment_op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.posts')),
            ],
        ),
    ]
