# Generated by Django 2.1 on 2018-09-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='USERNAME',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
