# Generated by Django 2.2 on 2019-05-18 16:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20190512_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_votes',
            name='upvoted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 22, 3, 11, 698706)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 22, 3, 11, 697704)),
        ),
        migrations.AlterUniqueTogether(
            name='post_votes',
            unique_together={('user_id', 'post_vote')},
        ),
    ]
