# Generated by Django 2.1 on 2018-10-09 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='TITLE',
            new_name='post_heading',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='POST',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_body',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_id',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='post_op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
