# Generated by Django 2.1 on 2018-10-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181009_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
