# Generated by Django 2.1.3 on 2018-12-15 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181010_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 11, 34, 0, 123463)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_heading',
            field=models.CharField(max_length=150),
        ),
    ]
