# Generated by Django 2.1.3 on 2018-12-15 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181215_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 13, 2, 6, 977217)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 13, 2, 6, 976199)),
        ),
    ]
